2024-12-07 15:21:42,419 - INFO     ->  1  -  .  -  .   - No auctions available
2024-12-07 15:21:42,723 - INFO     ->  2  -  .  -  .   - No auctions available
2024-12-07 15:21:43,087 - INFO     ->  3  -  .  -  .   - Auction retrieved: https://www.hacienda.gob.es/es-ES/Areas%20Tematicas/Patrimonio%20del%20Estado/Gestion%20Patrimonial%20del%20Estado/Paginas/Subastas/DEH-Alicante/Subasta-DEH-Alicante-2024-2.aspx
2024-12-07 15:21:43,200 - ERROR    ->  3  -  .  -  .   - Failed to find list of lands on Pliego or Anexo.
Traceback (most recent call last):
  File "/home/miguel/CodingProjects/ScrapingFincasHacienda/scrapingFincasHacienda/Hacienda/pliego_url.py", line 28, in get_pliego
    pliego = soup.find("a", href=const.PLIEGO_PATTERN).get("href")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
2024-12-07 15:21:43,466 - INFO     ->  4  -  .  -  .   - No auctions available
2024-12-07 15:21:43,987 - INFO     ->  5  -  .  -  .   - No auctions available
2024-12-07 15:21:44,350 - INFO     ->  6  -  .  -  .   - No auctions available
2024-12-07 15:21:44,652 - INFO     ->  7  -  .  -  .   - No auctions available
2024-12-07 15:21:45,228 - INFO     ->  8  -  .  -  .   - No auctions available
2024-12-07 15:21:45,631 - INFO     ->  9  -  .  -  .   - No auctions available
2024-12-07 15:21:45,912 - INFO     ->  10 -  .  -  .   - Auction retrieved: https://www.hacienda.gob.es/es-ES/Areas%20Tematicas/Patrimonio%20del%20Estado/Gestion%20Patrimonial%20del%20Estado/Paginas/Subastas/DEH-CACERES/Subasta-bienes-inmuebles.aspx
2024-12-07 15:21:48,312 - INFO     ->  10 -  .  -  .   - List of lands: https://www.hacienda.gob.es/DGPatrimonio/Gestión%20Patrimonial/subastas/DEH-CACERES/Pliego.pdf.xsig.pdf.
2024-12-07 15:21:49,028 - INFO     ->  10 -  .  -  .   - Auction with id 'OIP_KYYY2CC6COTD4E5269GYQ6NUOE39' is NEW.
2024-12-07 15:21:49,416 - INFO     ->  10 -  .  -  .   - Successfully downloaded url_pliego_pdf https://www.hacienda.gob.es/DGPatrimonio/Gestión%20Patrimonial/subastas/DEH-CACERES/Pliego.pdf.xsig.pdf.
 Saved on /home/miguel/CodingProjects/ScrapingFincasHacienda/data/auction/2024-12-07_Delegation_10.pdf
2024-12-07 15:21:51,749 - WARNING  ->  10 -  1  -  .   - Failed to process the lote 1
2024-12-07 15:21:51,749 - INFO     ->  10 -  2  -  .   - ['4226002QD2742E0021IE'], 58292.0
2024-12-07 15:21:51,749 - INFO     ->  10 -  3  -  .   - ['8669202TJ4586N0001HZ'], 2006.0
2024-12-07 15:21:51,749 - INFO     ->  10 -  4  -  .   - ['0676014TJ4507N0001TY'], 2322.0
2024-12-07 15:21:51,749 - INFO     ->  10 -  5  -  .   - ['0676013TJ4507N0001LY'], 1609.05
2024-12-07 15:21:51,749 - WARNING  ->  10 -  6  -  .   - Failed to process the lote 6
2024-12-07 15:21:51,749 - INFO     ->  10 -  7  -  .   - ['5724008QD2752D0017QB'], 220957.12
2024-12-07 15:21:51,749 - INFO     ->  10 -  8  -  .   - ['10115A014090180000ZM'], 14088.03
2024-12-07 15:21:51,749 - INFO     ->  10 -  .  -  .   - Corroborated that auction is NEW.
2024-12-07 15:22:11,453 - INFO     ->  10 -  2  -  1   - Successfully downloaded PDF and KML of the land '4226002QD2742E0021IE' with coordinates '39°28'23.6"N 6°23'41.4"W' and data: {'localizacion': 'CL VIVIENDAS DE CAMINEROS Ndup-U Bl:21 Es:1 Pl:02 Pt:DCH\n10005 CACERES (CÁCERES)', 'provincia': 'CÁCERES', 'municipio': 'CACERES ', 'clase': 'Urbano', 'uso': 'Residencial', 'cultivo': None}.
2024-12-07 15:22:16,162 - INFO     ->  10 -  2  -  1   - Land '4226002QD2742E0021IE' is in 'CACERES' province. More precisely is on 'CÁCERES' locality with C.P. 10005
2024-12-07 15:22:32,051 - INFO     ->  10 -  2  -  1   - Screenshot of the land '4226002QD2742E0021IE' has been taken successfully.
2024-12-07 15:22:36,026 - INFO     ->  10 -  2  -  1   - The land '4226002QD2742E0021IE' has the next value 136320.44.
The report PDF has been downloaded because it's 'Rústico'.
2024-12-07 15:22:38,847 - INFO     ->  10 -  2  -  1   - Population info about land '4226002QD2742E0021IE' has been extracted successfully: Now -> 96215 /// Five years ago -> 96068
2024-12-07 15:22:40,486 - INFO     ->  10 -  2  -  1   - Land 4226002QD2742E0021IE is 'Urbano' instead of 'Rústico', so the class IneNumTransmisionesFincasRusticas won't be used to scrape anything.
2024-12-07 15:22:42,112 - INFO     ->  10 -  2  -  1   - Land 4226002QD2742E0021IE is 'Urbano' instead of 'Rústico', so the class Iberpix won't be used to scrape anything.
2024-12-07 15:23:30,805 - INFO     ->  10 -  2  -  1   - Enterprises near land '4226002QD2742E0021IE' located on C.P. 10005 have been extracted successfully: ['METKA EGN SPAIN SL.', 'CATELSA CACERES SA', 'PARIENTE CARRASCO INVERSIONES SL.', 'CERES MOTOR SL', 'A D GRUPO FELIPE PARIENTE SL', 'AD RECAMBIOS EXTREMADURA SIGLO XXI SL.', 'NOVOMOTOR CACERES SL', 'SANTANO AUTOMOCION SA', 'CONSTRUCCIONES SEVILLA NEVADO SA', 'ALIMENTACION CONPE SL', 'EURO ELECTRODOMESTICOS EXTREMADURA SL', 'CODERE APUESTAS EXTREMADURA SA.', 'INTERLUN SL', 'COHIDREX SL', 'ASFALTOS Y AGLOMERADOS SANTANO SOCIEDAD ANONIMA', 'ALMACENES NORBA SL.', 'SEBASTIAN SEVILLA NEVADO SL.', 'RAPID DOORS SL', 'COVEX PRODUCTOS ZOOSANITARIOS SL', 'DISTRIBUCIONES Y MARKETING CACEREÑOS SL', 'PEBETERO SERVICIOS Y FORMACION SL.', 'GESTION GLOBAL DE REPARACIONES DE INMUEBLES SL.', 'FISSA SEGURIDAD Y VIGILANCIA SL', 'DISTRIBUCION CERVEZAS DE CACERES SL', '']
2024-12-07 15:25:44,519 - ERROR    ->  16 -  1  -  1   - Failed to extract car and foot distance and time from '4226002QD2742E0021IE' - 'METKA EGN SPAIN SL.'.
Traceback (most recent call last):
  File "/home/miguel/CodingProjects/ScrapingFincasHacienda/scrapingFincasHacienda/GoogleMaps/GoogleMaps.py", line 148, in get_data_two_directions
    data_car = self.__get_distance_time_on_car()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/miguel/CodingProjects/ScrapingFincasHacienda/scrapingFincasHacienda/GoogleMaps/GoogleMaps.py", line 272, in __get_distance_time_on_car
    on_car_btn = self.find_element(
                 ^^^^^^^^^^^^^^^^^^
  File "/home/miguel/CodingProjects/ScrapingFincasHacienda/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 770, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/miguel/CodingProjects/ScrapingFincasHacienda/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/home/miguel/CodingProjects/ScrapingFincasHacienda/venv/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//button[.//img[@aria-label='En coche']]"}
  (Session info: chrome=131.0.6778.108); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x60a639e2134a <unknown>
#1 0x60a6399376e0 <unknown>
#2 0x60a6399863e6 <unknown>
#3 0x60a639986681 <unknown>
#4 0x60a6399cbb04 <unknown>
#5 0x60a6399aa48d <unknown>
#6 0x60a6399c8ed7 <unknown>
#7 0x60a6399aa203 <unknown>
#8 0x60a639978cc0 <unknown>
#9 0x60a639979c9e <unknown>
#10 0x60a639deed3b <unknown>
#11 0x60a639df2cc2 <unknown>
#12 0x60a639ddbb6c <unknown>
#13 0x60a639df3837 <unknown>
#14 0x60a639dc110f <unknown>
#15 0x60a639e105a8 <unknown>
#16 0x60a639e10770 <unknown>
#17 0x60a639e201c6 <unknown>
#18 0x77d7d909ca94 <unknown>
#19 0x77d7d9129c3c <unknown>

2024-12-07 15:25:47,615 - ERROR    ->  16 -  1  -  1   - Failed to extract car and foot distance and time from '4226002QD2742E0021IE' - 'CATELSA CACERES SA'.
Traceback (most recent call last):
  File "/home/miguel/CodingProjects/ScrapingFincasHacienda/scrapingFincasHacienda/GoogleMaps/GoogleMaps.py", line 145, in get_data_two_directions
    self.__search_to()
  File "/home/miguel/CodingProjects/ScrapingFincasHacienda/scrapingFincasHacienda/GoogleMaps/GoogleMaps.py", line 207, in __search_to
    to_input.clear()
  File "/home/miguel/CodingProjects/ScrapingFincasHacienda/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 117, in clear
    self._execute(Command.CLEAR_ELEMENT)
  File "/home/miguel/CodingProjects/ScrapingFincasHacienda/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webelement.py", line 402, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/miguel/CodingProjects/ScrapingFincasHacienda/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/home/miguel/CodingProjects/ScrapingFincasHacienda/venv/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=131.0.6778.108)
Stacktrace:
#0 0x5a803a14b34a <unknown>
#1 0x5a8039c616e0 <unknown>
#2 0x5a8039c3738f <unknown>
#3 0x5a8039cdc89d <unknown>
#4 0x5a8039cf288c <unknown>
#5 0x5a8039cd4203 <unknown>
#6 0x5a8039ca2cc0 <unknown>
#7 0x5a8039ca3c9e <unknown>
#8 0x5a803a118d3b <unknown>
#9 0x5a803a11ccc2 <unknown>
#10 0x5a803a105b6c <unknown>
#11 0x5a803a11d837 <unknown>
#12 0x5a803a0eb10f <unknown>
#13 0x5a803a13a5a8 <unknown>
#14 0x5a803a13a770 <unknown>
#15 0x5a803a14a1c6 <unknown>
#16 0x7e8ffc29ca94 <unknown>
#17 0x7e8ffc329c3c <unknown>

